# Generated by Django 3.2.25 on 2025-02-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.CreateModel(
            name='StudentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('date_captured', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facerecognition.student')),
            ],
        ),
    ]
